// Mocks generated by Mockito 5.4.4 from annotations
// in password_manager/test/providers/password/local_password_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:password_manager/models/password.dart' as _i5;
import 'package:password_manager/services/password_service.dart' as _i3;
import 'package:uuid/uuid.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUuid_0 extends _i1.SmartFake implements _i2.Uuid {
  _FakeUuid_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PasswordService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasswordService extends _i1.Mock implements _i3.PasswordService {
  MockPasswordService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Uuid get uuid => (super.noSuchMethod(
        Invocation.getter(#uuid),
        returnValue: _FakeUuid_0(
          this,
          Invocation.getter(#uuid),
        ),
      ) as _i2.Uuid);

  @override
  _i4.Future<List<_i5.Password>> getPasswords() => (super.noSuchMethod(
        Invocation.method(
          #getPasswords,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Password>>.value(<_i5.Password>[]),
      ) as _i4.Future<List<_i5.Password>>);

  @override
  _i4.Future<int> save(_i5.Password? pwd) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [pwd],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> update(_i5.Password? pwd) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [pwd],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> delete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [ids],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
